name: trigger
on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to release from'
        required: true
        default: 'master'
      version:
        description: 'Release version'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        token: ${{ secrets.GIT_PASSWORD }}
    - name: Release from given branch with given version
      run: |
        BRANCH=${{ github.event.inputs.branch }}
        VERSION=${{ github.event.inputs.version }}
        echo "Releasing $VERSION from $BRANCH branch"
        git checkout $BRANCH
        git config --global user.email "noreply@manorrock.com"
        git config --global user.name "Automated release"
        git commit -a -m "Releasing version $VERSION" --allow-empty
        git tag v$VERSION -f
        git push origin v$VERSION -f
